steps:
  - name: 'node'
    entrypoint: 'npm'
    id: Install
    args:
      - 'install'
    dir: 'src'
  # Add testing when you've added and modified tests to your case
  #- name: 'node'
  #  entrypoint: 'npm'
  #  id: Test
  #  args: ['test']
  #  dir: 'src'
  - name: 'docker'
    id: Build
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME', '.']
  - name: 'docker'
    id: Push
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        'gcr.io/$PROJECT_ID/$REPO_NAME',
        '--region',
        '$_REGION',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

substitutions:
  _SERVICE_NAME: 'cloud-run-ts-apollo-graphql'
  _REGION: 'europe-north1'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
