steps:
  - name: 'node'
    entrypoint: 'npm'
    id: Install
    args:
      - 'install'
    dir: 'src'
  # Add testing when you've added and modified tests to your case
  #- name: 'node'
  #  entrypoint: 'npm'
  #  id: Test
  #  args: ['test']
  #  dir: 'src'
  - name: 'docker'
    id: Build
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMAGE', '.']
  - name: 'docker'
    id: Push
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMAGE']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMAGE',
        '--region',
        '$_REGION',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

substitutions:
  _REGION: 'europe-north1'
  _SERVICE_NAME: 'cloud-run-ts-apollo-graphql'
  _IMAGE: 'my-image'
images: ['$_REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_IMAGE']
